Repository BHoM/SAP2000_Toolkit, pull requests merged in 2021-08, with the labels that each got.

#235 Fix error when pulling BarDeformationResults
  SAP2000_Adapter/CRUD/Read/Results/BarResults.cs
Labels: type:bug

#237 Compile against Adapter changes
  SAP2000_Adapter/CRUD/Read/Node.cs
  SAP2000_Adapter/CRUD/Read/Section.cs
Labels: type:compliance

#231 Add null check for node orientation when creating or updating nodes
  SAP2000_Adapter/CRUD/Create/Node.cs
Labels: type:compliance, type:feature
