Repository BHoM/SAP2000_Toolkit, pull requests merged in 2021-03, with the labels that each got.

#200 Align to BHoM_Adapter's AdapterId() method change
  SAP2000_Adapter/CRUD/Update/Bar.cs
Labels: size:S, status:do-not-merge, type:compliance

#202 Add load ids to fix Create Load issue
  SAP2000_Adapter/CRUD/Create/Loads.cs
Labels: type:bug

#209 Correcting call to AdapterId
  SAP2000_Adapter/CRUD/Update/Bar.cs
Labels: type:compliance

#219 Fixing Load read/create bugs
  SAP2000_Adapter/CRUD/Create/Loads.cs
  SAP2000_Adapter/CRUD/Read/Loads.cs
Labels: type:bug, type:feature

#220 Revert "Fixing Load read/create bugs"
  SAP2000_Adapter/CRUD/Create/Loads.cs
  SAP2000_Adapter/CRUD/Read/Loads.cs
Labels: type:bug

#222 Fixing read/create load bugs
  SAP2000_Adapter/CRUD/Create/Loads.cs
  SAP2000_Adapter/CRUD/Read/Loads.cs
Labels: type:bug
